name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Simulate test deployment
        run: python scripts/deploy.py test

  approve-prod:
    name: Await Prod Approval
    runs-on: ubuntu-latest
    needs: deploy-test
    environment:
      name: prod
    steps:
      - name: Pending approval
        run: echo "Awaiting production deployment approval"

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: approve-prod
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Simulate production deployment
        run: python scripts/deploy.py prod
